// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;
import ballerina/log;
import service1.service2;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The whole-number average score of Service2's current catalog
    #
    # + return - The computed average
    resource function get average() returns AverageScore|error {
        service2:Catalog catalog = check service2Client->/catalog.get();
        service2:Record[] records = catalog.data;
        int recordCount = records.length();
        log:printInfo("handled average request", recordCount = recordCount);
        if recordCount == 0 {
            return error("service2 catalog is empty; cannot compute an average");
        }
        int total = 0;
        foreach service2:Record item in records {
            total += item.score;
        }
        int average = total / recordCount;
        return {average};
    }

    # Catch-all for any path this service does not serve.
    #
    # + path - the unmatched request path
    # + return - a structured 404 body
    resource function 'default [string... path]() returns http:NotFound {
        Error body = {
            code: 404,
            message: "Not Found",
            description: "Service1 does not serve this path.",
            moreInfo: "specs/design/components/service1/openapi.yaml"
        };
        return <http:NotFound>{body};
    }
}

public type AverageScore record {
    # Sum of every record's score divided by the record count, remainder discarded
    int average;
};
