// AUTO-GENERATED FILE.
// This file is auto-generated by the Ballerina OpenAPI tool.

import ballerina/http;

listener http:Listener ep0 = new (9090);

service / on ep0 {
    # The current catalog of scored records
    #
    # + return - The catalog matching the current mode
    resource function get catalog() returns Catalog {
        return currentCatalog();
    }

    # Switch between full and empty catalog mode
    #
    # + return - returns can be any of following types
    # http:Ok (Mode switched)
    # http:BadRequest (Invalid mode value)
    resource function put operations/mode(@http:Payload ModeChange payload) returns Catalog|ErrorBadRequest {
        Catalog|Error switchResult = switchMode(payload.mode);
        if switchResult is Error {
            return {body: switchResult};
        }
        return switchResult;
    }
}

public type ModeChange record {|
    string mode;
|};

public type Error record {|
    # HTTP or application error code
    int code;
    # short human-readable label
    string message;
    # detailed explanation
    string description?;
    # URI to documentation
    string moreInfo?;
|};

public type Record record {|
    int id;
    string name;
    int score;
|};

public type ErrorBadRequest record {|
    *http:BadRequest;
    Error body;
|};

public type Catalog record {|
    "full"|"empty" mode;
    Record[] data;
|};
